In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7, 6627, 8444, 97],
 [7, 6627, 8444, 7593],
 [7, 7583, 8444, 7169],
 [5471, 9710, 2690, 9672, 1404],
 [5471, 9710, 2690, 9672, 5203],
 [7012, 7, 8817, 8444, 2809],
 [9650, 4381, 3, 9672]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    7 6627 8444   97]
 [   0    0    0    0    7 6627 8444 7593]
 [   0    0    0    0    7 7583 8444 7169]
 [   0    0    0 5471 9710 2690 9672 1404]
 [   0    0    0 5471 9710 2690 9672 5203]
 [   0    0    0 7012    7 8817 8444 2809]
 [   0    0    0    0 9650 4381    3 9672]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\saswa\Downloads\Learning\py_scripts\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 351ms/step


array([[[-0.03170554,  0.02061096, -0.02961959, -0.0100885 ,
          0.01361537, -0.04205256,  0.00692767, -0.04208057,
         -0.04555695, -0.0215289 ],
        [-0.03170554,  0.02061096, -0.02961959, -0.0100885 ,
          0.01361537, -0.04205256,  0.00692767, -0.04208057,
         -0.04555695, -0.0215289 ],
        [-0.03170554,  0.02061096, -0.02961959, -0.0100885 ,
          0.01361537, -0.04205256,  0.00692767, -0.04208057,
         -0.04555695, -0.0215289 ],
        [-0.03170554,  0.02061096, -0.02961959, -0.0100885 ,
          0.01361537, -0.04205256,  0.00692767, -0.04208057,
         -0.04555695, -0.0215289 ],
        [ 0.0379212 , -0.02018504,  0.00346384, -0.00335189,
          0.00145011, -0.04748509,  0.0331088 ,  0.04448792,
         -0.0117304 ,  0.01231713],
        [-0.00566202,  0.04623264,  0.02771989, -0.00728133,
         -0.02866514, -0.02558154, -0.02367878, -0.00455264,
          0.02708327,  0.00968675],
        [-0.00552554, -0.03192047,  0.01586694, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,    7, 6627, 8444,   97])